version: '3.0'
services:
  nginx:
    image: "nginx:${NGINX_VERSION}"
    ports:
      - ${NGINX_HTTP_HOST_PORT}:80
    depends_on:
      - php
    environment:
      - TZ=${TZ}
    volumes:
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_CONF_DEFAULT_FILE}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${PROJECT_DIR}:/usr/share/nginx/html
    networks:
      - php_web_net
    hostname: nginx
    container_name: php_web_nginx
  php:
    build: 
      context: ./php7.4
      args:
        PHP_VERSION: "php:${PHP_VERSION}-fpm"
        CONTAINER_PACKAGE_URL: "${CONTAINER_PACKAGE_URL}"
    expose:
      - 9501
    links:
      - mysql
      - redis
    environment:
      - TZ=${TZ}
    volumes:
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.conf
      - ${PHP_WWW_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
      - ${PHP_INI_CONF_FILE}:/usr/local/etc/php/php.ini
      - ${PROJECT_DIR}:/var/www/html
    networks:
      - php_web_net
    hostname: php
    container_name: php_web_php
  mysql:
    image: "mysql/mysql-server:${MYSQL_VERSION}"
    ports:
      - ${MYSQL_HOST_PORT}:3306
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_CONFD_DIR}:/etc/mysql/conf.d
      - ${MYSQL_CONF_FILE}:/etc/mysql/my.cnf
    networks:
      - php_web_net
    hostname: mysql
    container_name: php_web_mysql
  redis:
    build:
      context: ./redis
      args:
        REDIS_VERSION: "redis:${REDIS_VERSION}"
        REDIS_HOST_PORT: "${REDIS_HOST_PORT}"
    ports:
      - ${REDIS_HOST_PORT}:6379
    environment:
      - TZ=${TZ}
    volumes:
      - ${REDIS_DATA_DIR}:/data
      - ${REDIS_LOG_DIR}:/logs
      - ${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf
    privileged: true
    networks:
      - php_web_net
    hostname: redis
    container_name: php_web_redis
  hyperf:
    image: hyperf/hyperf:${HYPERF_VERSION}-alpine-v3.15-swoole
    volumes:
      - ${PROJECT_DIR}:/data/project
    ports:
      - "${HYPERF_HOST_PORT}:9501"
    links:
      - mysql
      - redis
    privileged: true
    user: root
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh"]
    environment:
      TZ: "${TZ}"
    networks:
      - php_web_net
    hostname: hyperf
    container_name: php_web_hyperf
networks:
  php_web_net:
    driver: bridge
    ipam:
      driver: default
